model_path:
  large: 'E:\Streamlit App\env\Models\mistral-7b-instruct-v0.1.Q8_0.gguf'

embeddings_path: "BAAI/bge-large-en-v1.5"

model_type: "mistral"

model_config:
  max_new_tokens: 512
  temperature: 0
  context_length: 4096
  gpu_layers: 0

chat_history_path: 'E:\Streamlit App\env\chat_sessions'


